import type { Transaction, MonthlyRevenue } from '@/types/financeiro';

/**
 * Mais de 40 transações financeiras realistas para o módulo Financeiro.
 * Todos os dados são determinísticos para evitar incompatibilidades de hidratação.
 */
export const transacoesData: Transaction[] = [
  // ── RECEITAS (Mensalidades) ──────────────────────────
  {
    id: 'txn-001',
    tipo: 'receita',
    descricao: 'Mensalidade — João Victor Silva',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '01/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'João Victor Silva',
    alunoId: 1,
    recorrente: true,
  },
  {
    id: 'txn-002',
    tipo: 'receita',
    descricao: 'Mensalidade — Maria Clara Oliveira',
    categoria: 'mensalidade',
    valor: 349.90,
    data: '05/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Maria Clara Oliveira',
    alunoId: 2,
    recorrente: true,
  },
  {
    id: 'txn-003',
    tipo: 'receita',
    descricao: 'Mensalidade — Pedro Henrique Santos',
    categoria: 'mensalidade',
    valor: 99.90,
    data: '12/04/2026',
    vencimento: '10/04/2026',
    status: 'atrasado',
    metodo: 'boleto',
    alunoNome: 'Pedro Henrique Santos',
    alunoId: 3,
    recorrente: true,
  },
  {
    id: 'txn-004',
    tipo: 'receita',
    descricao: 'Mensalidade — Ana Carolina Costa',
    categoria: 'mensalidade',
    valor: 249.90,
    data: '20/03/2026',
    vencimento: '20/03/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Ana Carolina Costa',
    alunoId: 4,
    recorrente: true,
  },
  {
    id: 'txn-005',
    tipo: 'receita',
    descricao: 'Mensalidade — Gabriel Almeida Souza',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '10/04/2026',
    vencimento: '10/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Gabriel Almeida Souza',
    alunoId: 7,
    recorrente: true,
  },
  {
    id: 'txn-006',
    tipo: 'receita',
    descricao: 'Mensalidade — Isadora Martins Pereira',
    categoria: 'mensalidade',
    valor: 99.90,
    data: '05/04/2026',
    vencimento: '05/04/2026',
    status: 'pendente',
    metodo: 'boleto',
    alunoNome: 'Isadora Martins Pereira',
    alunoId: 8,
    recorrente: true,
  },
  {
    id: 'txn-007',
    tipo: 'receita',
    descricao: 'Mensalidade — Rafael Oliveira Nunes',
    categoria: 'mensalidade',
    valor: 349.90,
    data: '01/04/2026',
    vencimento: '01/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Rafael Oliveira Nunes',
    alunoId: 9,
    recorrente: true,
  },
  {
    id: 'txn-008',
    tipo: 'receita',
    descricao: 'Mensalidade — Larissa Moreira Gomes',
    categoria: 'mensalidade',
    valor: 349.90,
    data: '03/04/2026',
    vencimento: '03/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Larissa Moreira Gomes',
    alunoId: 14,
    recorrente: true,
  },
  {
    id: 'txn-009',
    tipo: 'receita',
    descricao: 'Mensalidade — Valentina Santos Freitas',
    categoria: 'mensalidade',
    valor: 349.90,
    data: '07/04/2026',
    vencimento: '07/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Valentina Santos Freitas',
    alunoId: 20,
    recorrente: true,
  },
  {
    id: 'txn-010',
    tipo: 'receita',
    descricao: 'Mensalidade — Thiago Rodrigues Lima',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '08/04/2026',
    vencimento: '08/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Thiago Rodrigues Lima',
    alunoId: 11,
    recorrente: true,
  },
  {
    id: 'txn-011',
    tipo: 'receita',
    descricao: 'Mensalidade — Daniel Costa Monteiro',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '12/04/2026',
    vencimento: '12/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Daniel Costa Monteiro',
    alunoId: 17,
    recorrente: true,
  },
  {
    id: 'txn-012',
    tipo: 'receita',
    descricao: 'Mensalidade — Gustavo Pereira Machado',
    categoria: 'mensalidade',
    valor: 99.90,
    data: '10/04/2026',
    vencimento: '05/04/2026',
    status: 'atrasado',
    metodo: 'boleto',
    alunoNome: 'Gustavo Pereira Machado',
    alunoId: 19,
    recorrente: true,
  },
  {
    id: 'txn-013',
    tipo: 'receita',
    descricao: 'Mensalidade — Manuela Duarte Correia',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '05/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Manuela Duarte Correia',
    alunoId: 22,
    recorrente: true,
  },
  {
    id: 'txn-014',
    tipo: 'receita',
    descricao: 'Mensalidade — Arthur Melo Pinheiro',
    categoria: 'mensalidade',
    valor: 349.90,
    data: '09/04/2026',
    vencimento: '09/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Arthur Melo Pinheiro',
    alunoId: 25,
    recorrente: true,
  },
  {
    id: 'txn-015',
    tipo: 'receita',
    descricao: 'Mensalidade — Laura Gomes Figueiredo',
    categoria: 'mensalidade',
    valor: 249.90,
    data: '14/04/2026',
    vencimento: '10/04/2026',
    status: 'pendente',
    metodo: 'boleto',
    alunoNome: 'Laura Gomes Figueiredo',
    alunoId: 26,
    recorrente: true,
  },
  {
    id: 'txn-016',
    tipo: 'receita',
    descricao: 'Mensalidade — Davi Lopes Cunha',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '11/04/2026',
    vencimento: '11/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Davi Lopes Cunha',
    alunoId: 27,
    recorrente: true,
  },
  {
    id: 'txn-017',
    tipo: 'receita',
    descricao: 'Mensalidade — Alice Mendes Torres',
    categoria: 'mensalidade',
    valor: 99.90,
    data: '02/04/2026',
    vencimento: '02/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Alice Mendes Torres',
    alunoId: 28,
    recorrente: true,
  },
  {
    id: 'txn-018',
    tipo: 'receita',
    descricao: 'Mensalidade — Isabella Castro Fernandes',
    categoria: 'mensalidade',
    valor: 189.90,
    data: '06/04/2026',
    vencimento: '06/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Isabella Castro Fernandes',
    alunoId: 30,
    recorrente: true,
  },

  // ── RECEITAS (Outros) ────────────────────────────────
  {
    id: 'txn-019',
    tipo: 'receita',
    descricao: 'Matrícula — Lucas Gabriel Ferreira',
    categoria: 'matricula',
    valor: 149.90,
    data: '01/03/2026',
    vencimento: '01/03/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Lucas Gabriel Ferreira',
    alunoId: 5,
    recorrente: false,
  },
  {
    id: 'txn-020',
    tipo: 'receita',
    descricao: 'Sessão Personal — João Victor Silva',
    categoria: 'personal',
    valor: 120.00,
    data: '08/04/2026',
    vencimento: '08/04/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'João Victor Silva',
    alunoId: 1,
    recorrente: false,
  },
  {
    id: 'txn-021',
    tipo: 'receita',
    descricao: 'Pacote 10 sessões Personal — Maria Clara Oliveira',
    categoria: 'personal',
    valor: 950.00,
    data: '10/04/2026',
    vencimento: '10/04/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Maria Clara Oliveira',
    alunoId: 2,
    recorrente: false,
  },
  {
    id: 'txn-022',
    tipo: 'receita',
    descricao: 'Day Use — Visitante',
    categoria: 'avulso',
    valor: 45.00,
    data: '05/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'dinheiro',
    recorrente: false,
  },
  {
    id: 'txn-023',
    tipo: 'receita',
    descricao: 'Venda de Whey Protein 900g',
    categoria: 'produto',
    valor: 159.90,
    data: '07/04/2026',
    vencimento: '07/04/2026',
    status: 'pago',
    metodo: 'debito',
    recorrente: false,
  },
  {
    id: 'txn-024',
    tipo: 'receita',
    descricao: 'Venda de Creatina 300g',
    categoria: 'produto',
    valor: 89.90,
    data: '09/04/2026',
    vencimento: '09/04/2026',
    status: 'pago',
    metodo: 'pix',
    recorrente: false,
  },
  {
    id: 'txn-025',
    tipo: 'receita',
    descricao: 'Aulão de Spinning — Evento Especial',
    categoria: 'evento',
    valor: 680.00,
    data: '12/04/2026',
    vencimento: '12/04/2026',
    status: 'pago',
    metodo: 'pix',
    recorrente: false,
  },

  // ── DESPESAS ─────────────────────────────────────────
  {
    id: 'txn-026',
    tipo: 'despesa',
    descricao: 'Aluguel — Abril 2026',
    categoria: 'aluguel',
    valor: 8500.00,
    data: '01/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'boleto',
    recorrente: true,
  },
  {
    id: 'txn-027',
    tipo: 'despesa',
    descricao: 'Folha de Pagamento — Abril 2026',
    categoria: 'salario',
    valor: 24800.00,
    data: '05/04/2026',
    vencimento: '05/04/2026',
    status: 'pago',
    metodo: 'boleto',
    recorrente: true,
  },
  {
    id: 'txn-028',
    tipo: 'despesa',
    descricao: 'Conta de Energia — Abril 2026',
    categoria: 'agua_luz',
    valor: 2350.00,
    data: '10/04/2026',
    vencimento: '15/04/2026',
    status: 'pago',
    metodo: 'boleto',
    recorrente: true,
  },
  {
    id: 'txn-029',
    tipo: 'despesa',
    descricao: 'Conta de Água — Abril 2026',
    categoria: 'agua_luz',
    valor: 480.00,
    data: '10/04/2026',
    vencimento: '15/04/2026',
    status: 'pago',
    metodo: 'boleto',
    recorrente: true,
  },
  {
    id: 'txn-030',
    tipo: 'despesa',
    descricao: 'Manutenção Esteira Profissional',
    categoria: 'manutencao',
    valor: 1200.00,
    data: '08/04/2026',
    vencimento: '08/04/2026',
    status: 'pago',
    metodo: 'pix',
    recorrente: false,
  },
  {
    id: 'txn-031',
    tipo: 'despesa',
    descricao: 'Google Ads — Campanha Abril',
    categoria: 'marketing',
    valor: 1500.00,
    data: '01/04/2026',
    vencimento: '01/04/2026',
    status: 'pago',
    metodo: 'cartao',
    recorrente: true,
  },
  {
    id: 'txn-032',
    tipo: 'despesa',
    descricao: 'Instagram Ads — Abril',
    categoria: 'marketing',
    valor: 800.00,
    data: '01/04/2026',
    vencimento: '01/04/2026',
    status: 'pago',
    metodo: 'cartao',
    recorrente: true,
  },
  {
    id: 'txn-033',
    tipo: 'despesa',
    descricao: 'Compra 2x Halteres 30kg',
    categoria: 'equipamento',
    valor: 890.00,
    data: '03/04/2026',
    vencimento: '03/04/2026',
    status: 'pago',
    metodo: 'pix',
    recorrente: false,
  },
  {
    id: 'txn-034',
    tipo: 'despesa',
    descricao: 'Sistema de Gestão — Assinatura Mensal',
    categoria: 'sistema',
    valor: 299.90,
    data: '01/04/2026',
    vencimento: '01/04/2026',
    status: 'pago',
    metodo: 'cartao',
    recorrente: true,
  },
  {
    id: 'txn-035',
    tipo: 'despesa',
    descricao: 'Material de Limpeza',
    categoria: 'outros',
    valor: 320.00,
    data: '06/04/2026',
    vencimento: '06/04/2026',
    status: 'pago',
    metodo: 'dinheiro',
    recorrente: false,
  },
  {
    id: 'txn-036',
    tipo: 'despesa',
    descricao: 'Reparo Ar Condicionado — Sala Musculação',
    categoria: 'manutencao',
    valor: 750.00,
    data: '11/04/2026',
    vencimento: '15/04/2026',
    status: 'pendente',
    metodo: 'pix',
    recorrente: false,
  },
  {
    id: 'txn-037',
    tipo: 'despesa',
    descricao: 'Contabilidade — Honorários Abril',
    categoria: 'outros',
    valor: 1100.00,
    data: '10/04/2026',
    vencimento: '10/04/2026',
    status: 'pago',
    metodo: 'boleto',
    recorrente: true,
  },
  // Mais receitas para adicionar variedade
  {
    id: 'txn-038',
    tipo: 'receita',
    descricao: 'Mensalidade — Beatriz Lima Rocha',
    categoria: 'mensalidade',
    valor: 449.90,
    data: '28/03/2026',
    vencimento: '28/03/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Beatriz Lima Rocha',
    alunoId: 6,
    recorrente: true,
  },
  {
    id: 'txn-039',
    tipo: 'receita',
    descricao: 'Mensalidade — Sophia Alves Cardoso',
    categoria: 'mensalidade',
    valor: 449.90,
    data: '25/03/2026',
    vencimento: '25/03/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Sophia Alves Cardoso',
    alunoId: 18,
    recorrente: true,
  },
  {
    id: 'txn-040',
    tipo: 'receita',
    descricao: 'Mensalidade — Helena Vieira Campos',
    categoria: 'mensalidade',
    valor: 449.90,
    data: '30/03/2026',
    vencimento: '30/03/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Helena Vieira Campos',
    alunoId: 24,
    recorrente: true,
  },
  {
    id: 'txn-041',
    tipo: 'receita',
    descricao: 'Mensalidade — Felipe Nascimento Cruz',
    categoria: 'mensalidade',
    valor: 249.90,
    data: '18/03/2026',
    vencimento: '18/03/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Felipe Nascimento Cruz',
    alunoId: 15,
    recorrente: true,
  },
  {
    id: 'txn-042',
    tipo: 'receita',
    descricao: 'Mensalidade — Bruno Henrique Azevedo',
    categoria: 'mensalidade',
    valor: 249.90,
    data: '22/03/2026',
    vencimento: '22/03/2026',
    status: 'pago',
    metodo: 'pix',
    alunoNome: 'Bruno Henrique Azevedo',
    alunoId: 21,
    recorrente: true,
  },
  {
    id: 'txn-043',
    tipo: 'receita',
    descricao: 'Mensalidade — Julia Fernandes Araújo',
    categoria: 'mensalidade',
    valor: 449.90,
    data: '15/03/2026',
    vencimento: '15/03/2026',
    status: 'pago',
    metodo: 'cartao',
    alunoNome: 'Julia Fernandes Araújo',
    alunoId: 12,
    recorrente: true,
  },
];

/**
 * Dados de receita e despesa mensal para o gráfico de barras.
 * Últimos 6 meses de dados.
 */
export const monthlyRevenueData: MonthlyRevenue[] = [
  { mes: 'Nov', receita: 38200, despesa: 31500 },
  { mes: 'Dez', receita: 42800, despesa: 33200 },
  { mes: 'Jan', receita: 35600, despesa: 30800 },
  { mes: 'Fev', receita: 39400, despesa: 31200 },
  { mes: 'Mar', receita: 44100, despesa: 32600 },
  { mes: 'Abr', receita: 47850, despesa: 42990 },
];
